name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      id: create_tunnel
      run: .\ngrok\ngrok.exe tcp 3389 --log=stdout | Out-File ngrok_log.txt
    - name: Extract Ngrok URL
      id: extract_url
      run: |
        Start-Sleep -s 10 # wait for ngrok to initialize
        $url = Select-String "tcp://" ngrok_log.txt -SimpleMatch | Select-Object -First 1
        echo "NGROK_URL=$url" >> $env:GITHUB_ENV
    - name: Show Ngrok URL
      run: echo "Ngrok URL is ${{ env.NGROK_URL }}"
